apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data: 
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:         #these are replicaset service labels
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:       #these are used to select the pod to create replicas
    matchLabels:  #matchlabels should match with pod level labels 
      app: backend
      tier: api
      project: expense
  template:       #this is the pod definition
    metadata:
      labels:     #these labels are belongs to pod
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: ramanji4/backend:v1
        envFrom:
          configMapRef:
            name: backend

---

apiVersion: v1
apiVersion: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080